version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" # Port laptop berubah jadi 5433, port dalam docker tetap 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
